[theme]
base = "dark"
primaryColor = "#1F77B4"  # Altere para a cor desejada
backgroundColor = "black"  # Permitirá aplicar gradiente
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
